hash-format = "sha256"

[[files]]
file = ".gitmodules"

[[files]]
file = "config/CoroUtil/General.toml"

[[files]]
file = "config/EmiLootConfig_v1.json"

[[files]]
file = "config/Weather2/Debug.toml"

[[files]]
file = "config/Weather2/Misc.toml"

[[files]]
file = "config/Weather2/Particle.toml"

[[files]]
file = "config/Weather2/Sand.toml"

[[files]]
file = "config/Weather2/Snow.toml"

[[files]]
file = "config/Weather2/Sound.toml"

[[files]]
file = "config/Weather2/Storm.toml"

[[files]]
file = "config/Weather2/Tornado.toml"

[[files]]
file = "config/Weather2/Wind.toml"

[[files]]
file = "config/ambientsounds-client.json"

[[files]]
file = "config/amendments-client.toml"

[[files]]
file = "config/amendments-common.toml"

[[files]]
file = "config/antique-atlas.toml"

[[files]]
file = "config/appleskin-client.toml"

[[files]]
file = "config/badoptimizations.txt"

[[files]]
file = "config/bcc-common.toml"

[[files]]
file = "config/canary.properties"

[[files]]
file = "config/cardinal-components-api.properties"

[[files]]
file = "config/cccbridge.properties"

[[files]]
file = "config/charmofundying-server.toml"

[[files]]
file = "config/chat_heads.json5"

[[files]]
file = "config/collective.json5"

[[files]]
file = "config/comforts-server.toml"

[[files]]
file = "config/computercraft-client.toml"

[[files]]
file = "config/concentration-client.toml"

[[files]]
file = "config/copycats-client.toml"

[[files]]
file = "config/copycats-common.toml"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/create-common.toml"

[[files]]
file = "config/create-track-map.json"

[[files]]
file = "config/create-train-perspective.json"

[[files]]
file = "config/createcafe-common.toml"

[[files]]
file = "config/cull-less-leaves.json"

[[files]]
file = "config/curios-client.toml"

[[files]]
file = "config/curios-common.toml"

[[files]]
file = "config/doubledoors.json5"

[[files]]
file = "config/dynamic_fps.json"

[[files]]
file = "config/elytra-trims.json"

[[files]]
file = "config/embeddium-fingerprint.json"

[[files]]
file = "config/embeddium-mixins.properties"

[[files]]
file = "config/embeddium-options.json"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/emitrades.json5"

[[files]]
file = "config/endermail-client.toml"

[[files]]
file = "config/endermail-common.toml"

[[files]]
file = "config/entityculling.json"

[[files]]
file = "config/fabric/indigo-renderer.properties"

[[files]]
file = "config/ferritecore-mixin.toml"

[[files]]
file = "config/figura.json"

[[files]]
file = "config/flywheel-client.toml"

[[files]]
file = "config/fml.toml"

[[files]]
file = "config/forge-client.toml"

[[files]]
file = "config/fpsreducer/fpsreducer-client.toml"

[[files]]
file = "config/gravestone-client.toml"

[[files]]
file = "config/harvest_with_ease-common.toml"

[[files]]
file = "config/harvestwithease-common.toml"

[[files]]
file = "config/healthindicatortxf.json"

[[files]]
file = "config/highlighter-common.toml"

[[files]]
file = "config/immediatelyfast.json"

[[files]]
file = "config/jei/blacklist.cfg"

[[files]]
file = "config/jei/jei-client.ini"

[[files]]
file = "config/jei/jei-colors.ini"

[[files]]
file = "config/jei/jei-debug.ini"

[[files]]
file = "config/jei/jei-mod-id-format.ini"

[[files]]
file = "config/jei/recipe-category-sort-order.ini"

[[files]]
file = "config/ktnilcks-client.toml"

[[files]]
file = "config/legendarytooltips-common.toml"

[[files]]
file = "config/letmedespawn.json"

[[files]]
file = "config/lithium.properties"

[[files]]
file = "config/modernfix-common.toml"

[[files]]
file = "config/modernfix-mixins.properties"

[[files]]
file = "config/moonlight-client.toml"

[[files]]
file = "config/moonlight-common.toml"

[[files]]
file = "config/mutil-client.toml"

[[files]]
file = "config/oculus.properties"

[[files]]
file = "config/packetfixer.properties"

[[files]]
file = "config/polymorph-integrations.toml"

[[files]]
file = "config/qualitysounds.json"

[[files]]
file = "config/railways-client.toml"

[[files]]
file = "config/railways-common.toml"

[[files]]
file = "config/roughlyenoughitems/changelog.txt"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/roughlyenoughitems/hints.json"

[[files]]
file = "config/roughlyenoughitems/pinyin.properties"

[[files]]
file = "config/roughlyenoughitems/pinyin_double.properties"

[[files]]
file = "config/rrls.toml"

[[files]]
file = "config/saturn-optimizations.toml"

[[files]]
file = "config/seamless_loading_screen.json"

[[files]]
file = "config/simple-rpc/server-entries.toml"

[[files]]
file = "config/simple-rpc/simple-rpc.toml"

[[files]]
file = "config/snowundertrees-common.toml"

[[files]]
file = "config/sodium-extra-options.json"

[[files]]
file = "config/sodium-extra.properties"

[[files]]
file = "config/spyglass_of_curios.toml"

[[files]]
file = "config/supplementaries-client.toml"

[[files]]
file = "config/supplementaries-common.toml"

[[files]]
file = "config/surveyor.toml"

[[files]]
file = "config/tetra.toml"

[[files]]
file = "config/veinmining-client.toml"

[[files]]
file = "config/veinmining-common.toml"

[[files]]
file = "config/veinmining-server.toml"

[[files]]
file = "config/voicechat-client.toml"

[[files]]
file = "config/voicechat/translations.properties"

[[files]]
file = "config/voicechat/voicechat-client.properties"

[[files]]
file = "config/voicechat/voicechat-server.properties"

[[files]]
file = "config/waila/blacklist.json"

[[files]]
file = "config/waila/extra/energy_blacklist.json"

[[files]]
file = "config/waila/extra/fluid_blacklist.json"

[[files]]
file = "config/waila/extra/item_blacklist.json"

[[files]]
file = "config/waila/extra/progress_blacklist.json"

[[files]]
file = "config/waila/plugin_toggle.json"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/waterdripsound-client.toml"

[[files]]
file = "kubejs/README.txt"

[[files]]
file = "kubejs/assets/minecraft/lang/de_de.json"

[[files]]
file = "kubejs/assets/minecraft/lang/en_us.json"

[[files]]
file = "kubejs/assets/ticketing/models/block/ticket_machine_with_ticket.json"

[[files]]
file = "kubejs/assets/ticketing/models/block/ticket_machine_without_ticket.json"

[[files]]
file = "kubejs/assets/ticketing/models/block/ticket_reader.json"

[[files]]
file = "kubejs/assets/ticketing/models/item/ticket_machine.json"

[[files]]
file = "kubejs/assets/ticketing/models/item/ticket_reader.json"

[[files]]
file = "kubejs/assets/ticketing/sounds.json"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_fwoop1.ogg"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_fwoop2.ogg"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_fwoop3.ogg"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_fwoop4.ogg"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_supertear.ogg"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_tear1.ogg"

[[files]]
file = "kubejs/assets/ticketing/sounds/ticket_tear2.ogg"

[[files]]
file = "kubejs/assets/ticketing/textures/block/ticket_machine.png"

[[files]]
file = "kubejs/assets/ticketing/textures/block/ticket_reader.png"

[[files]]
file = "kubejs/assets/ticketing/textures/item/blank_ticket.png"

[[files]]
file = "kubejs/assets/ticketing/textures/item/ticket.png"

[[files]]
file = "kubejs/assets/ticketing/textures/item/ticket_machine.png"

[[files]]
file = "kubejs/assets/ticketing/textures/item/ticket_reader.png"

[[files]]
file = "kubejs/client_scripts/jsconfig.json"

[[files]]
file = "kubejs/config/client.properties"

[[files]]
file = "kubejs/config/common.properties"

[[files]]
file = "kubejs/config/probe-settings.json"

[[files]]
file = "kubejs/server_scripts/jsconfig.json"

[[files]]
file = "kubejs/server_scripts/src/chat.js"

[[files]]
file = "kubejs/server_scripts/src/info.json"

[[files]]
file = "kubejs/server_scripts/src/recipes.js"

[[files]]
file = "kubejs/server_scripts/src/ticket_machine.js"

[[files]]
file = "kubejs/server_scripts/src/ticket_reader.js"

[[files]]
file = "kubejs/startup_scripts/jsconfig.json"

[[files]]
file = "kubejs/startup_scripts/src/ticketing.js"

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/antique-atlas-4.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/charm-of-undying.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/cobweb.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/concentration.pw.toml"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-cafe.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-pattern-schematics.pw.toml"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create-tfmg.pw.toml"
metafile = true

[[files]]
file = "mods/create-track-map.pw.toml"
metafile = true

[[files]]
file = "mods/create-train-perspective.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/ender-mail.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs+cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
metafile = true

[[files]]
file = "mods/longer-chat-history.pw.toml"
metafile = true

[[files]]
file = "mods/megane-forge.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/mutil.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/northerncompass.pw.toml"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/quality-sounds.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
metafile = true

[[files]]
file = "mods/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spyglass-of-curios.pw.toml"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tetra-extras.pw.toml"
metafile = true

[[files]]
file = "mods/tetra.pw.toml"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
metafile = true

[[files]]
file = "mods/waterdripsound.pw.toml"
metafile = true

[[files]]
file = "mods/weather-storms-tornadoes.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "resourcepacks/eclectic-trove-legendary-tooltips.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/enchant-icons-countxd.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
metafile = true
