name = "Minebox Neo"
author = "der_frühling"
version = "3.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecea8c23f47d00688676a744fee50f853ad1110a65f2098b39d11800c76e9eac"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
