on:
  push:
  release:
    types: [published]

name: Build Modpack

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download packwiz
      uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
      with:
        repo: packwiz/packwiz
        name: Linux 64-bit x86
        latest: true
        path: /tmp
    - name: Build Pack
      run: |
        chmod +x /tmp/packwiz && /tmp/packwiz modrinth export -o minebox.mrpack
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minebox Modrinth Pack
        path: minebox.mrpack
        if-no-files-found: error
  publish-pack:
    runs-on: ubuntu-latest
    needs: build-pack
    if: github.event.action == 'release'
    environment: Modrinth
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Minebox Modrinth Pack
        path: .
    - name: Toml Select - TOML Field Extractor Action
      # You may pin to the exact commit or the version.
      # uses: sravinet/toml-select@fe2e680f88a09851a0cd887dba0bbd19d3babe11
      uses: sravinet/toml-select@v1.0.1
      id: introspection
      with:
        # The path to the TOML file.
        file: pack.toml
        # The field to extract from the TOML file.
        field: version
    - name: Upload to Modrinth
      uses: Warped-Modding/mrpack-upload@0.0.9
      with:
        name: v${{ steps.introspection.outputs.value }}
        version-number: ${{ steps.introspection.outputs.value }}
        project-id: K0m6xO6q
        pack-filename: minebox.mrpack
        loaders: forge
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        
    
