on: [push]

name: Build Modpack

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download packwiz
      uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
      with:
        repo: packwiz/packwiz
        name: Linux 64-bit x86
        latest: true
        path: /tmp
    - name: Build Pack
      run: |
        /tmp/packwiz modrinth export -o minebox.mrpack
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minebox Modrinth Pack
        path: minebox.mrpack
        if-no-files-found: error
    
